#!/bin/bash

echo "scp -i ~/.ssh/udp2-ssh-bastion.pem /home/simon/.ssh/udp2-ssh-privatesubnet.pem ec2-user@$1:"
scp -i ~/.ssh/udp2-ssh-bastion.pem /home/simon/.ssh/udp2-ssh-privatesubnet.pem ec2-user@$1:
echo "ssh -i ~/.ssh/udp2-ssh-bastion.pem ec2-user@$1"
ssh -i ~/.ssh/udp2-ssh-bastion.pem ec2-user@$1
