#!/bin/bash

echo "scp -i ~/.ssh/udp2-ssh-bastion.pem /home/simon/.ssh/udp2-ssh-privatesubnet.pem ubuntu@$1:"
scp -i ~/.ssh/udp2-ssh-bastion.pem /home/simon/.ssh/udp2-ssh-privatesubnet.pem ubuntu@$1:
echo "ssh -i ~/.ssh/udp2-ssh-bastion.pem ubuntu@$1"
ssh -i ~/.ssh/udp2-ssh-bastion.pem ubuntu@$1
