#!/bin/bash

stackid="$(cat stack-id)"
cmd="
    aws cloudformation $1-stack \
    --stack-name $stackid-$2 \
    $( [[ "$1" == delete ]] || echo "--template-body file://$2.yml" ) \
    $( [[ "$1" == delete ]] || echo "--parameters file://$2_params.json" ) \
    --region=us-west-2
"
echo $cmd
$cmd
